extern U0 printf(U8i *fmt,...);
#link "ncurses"
#link "tinfo"
//#include "szgsdyh"
"HELLO \n";
U8i chr=10;
"%n",((1000000.0/2.0)/(((100000.0/2.0)/2.0)/((10000.0/2.0)/((10000.0/2.0)/((10000.0/2.0)/((10000.0/2.0)/((1000.0/2.0)/((100.0/2.0)/(10.0/2.0)))))))));
I32i union I32 {
	U8i u8[4];
};
I32 x=0x1ff;
"%d\n",x.u8[0];
"%d\n",x.u8[1];
I32 arr[10];
for(x=0;x!=10;x++) arr[x]=x;
for(x=0;x!=10;x++) "%d\n",arr[x];